### ISSUE TITLE
Migration to another server

### ISSUE THREAD

**Issue by tigexplorer** [kanboard/forum#127]
Hi, I've found no information about the steps for migration a kanboard installation/db from one to another server.

Is it possible to go thru this steps:

 * backup/restore the mysql db
 * copy the kanboard directory to the new server
 * make changes in config.php, if necessary
 * starting the web server and login to kanboard

Is there a mistake or an missing step?
How about changing the domain name by the migration?

**Comment by creecros** [comment]
> * backup/restore the mysql db

Server 1:
`mysqldump --databases kanboard > dump.sql`
`kanboard' is the name of your database, i'm assuming it is named kanboard.

Copy file: `dump.sql` to new server.

Server 2:
`mysql < dump.sql`

> * copy the kanboard directory to the new server

If you can't figure out how to copy a file from one server to the other, we may have a problem here.
So, I'll assume you know how to copy files. Unless you have edited the Kanboard Source code, there is no need to copy the kanboard directory, just make a fresh install. Then copy the below files and folder.

* Copy the data folder (this will hold all your files, i.e. images, etc...if sqlite, your DB will be in here.)
* Copy the plugins folder (not really neccassary, you could just reinstall your plugins)
* Copy the config.php as well. (if you haven't made many edits in here, you might not need to do this)

Place them where they belong on the new server.

> * make changes in config.php, if necessary

In shell? go to the directory that the config.php is in, type `vi config.php` or `nano config.php` assuming your in shell and assuming you have a basic editor installed. You'll need to change your DB in here, so that it points to the new one. 

> * starting the web server and login to kanboard

depends on your server setup...

**Comment by tigexplorer** [comment]
Thanx, it seems, that the migration works flawless.
